version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  build-source:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          lts: true
          install-yarn: true
      - node/install-packages:
          pkg-manager: 'yarn'
      - run:
          name: Build source
          command: yarn build-prod
      - run:
          name: Upload artifact
          command: |
            (cd build; zip -r ../build.zip *)
            cd ..
            cp -r build.zip /tmp
      - store_artifacts:
          path: /tmp/build.zip
      - run:
          name: Get artifacts
          command: |
            artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/PhucNVH/trochuyenonline-frontend/latest/artifacts" \
            -H "Accept: application/json" \
            -u "$CIRCLE_API_TOKEN:")
            echo "export ARTIFACT_RESPONSE=$artifacts" >> $BASH_ENV

  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - add_ssh_keys:
          fingerprints:
            - '73:31:fc:07:45:b3:1f:60:45:0e:0f:17:48:1c:66:8f'
      - run:
          name: Download artifact
          command: |
            curl -H "Circle-Token: a93d4d8eafd4f6c2a5818bd8e1ea74b06f777ce9" https://circleci.com/api/v1.1/project/github/PhucNVH/trochuyenonline-frontend/$(($CIRCLE_BUILD_NUM-1))/artifacts \
            | grep -o 'https://[^"]*'  \
            | wget --verbose --header "Circle-Token: a93d4d8eafd4f6c2a5818bd8e1ea74b06f777ce9" --input-file -
      - run:
          name: Checking files
          command: ls
      - run:
          name: Adding host to known_hosts
          command: ssh-keyscan -H 52.221.183.205 >> ~/.ssh/known_hosts
      - run:
          name: Uploading to server
          command: scp -r ./build.zip tco@52.221.183.205:/home/tco/builds/tco/web
      - run:
          name: Setting up new site
          command: ssh tco@52.221.183.205 "sh /home/tco/builds/tco/web/tco.sh"

workflows:
  build-app:
    jobs:
      - node/test:
          pkg-manager: 'yarn'
          version: '14.16.0'
          filters:
            branches:
              only:
                - prod

      - build-source:
          filters:
            branches:
              only:
                - prod
                - main

      - deploy:
          requires:
            - build-source
          filters:
            branches:
              only:
                - prod
                - main
